services:
  postgresdb:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mvcteste
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
    restart: unless-stopped    
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/app      
    working_dir: /app
    command: >
      sh -c "
      if [ -f composer.json ]; then
        php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" &&
        php composer-setup.php &&
        php -r \"unlink('composer-setup.php');\" &&
        php composer.phar install
      fi &&
      php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"

volumes:
  pgdata:
  redis_data: